events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        # Endpointy dotyczące relacji i podstawowych danych lecą do pg-service
        location /api/users/ {
            proxy_pass http://pg-service:3001;
        }
        
        location /api/posts/ {
            proxy_pass http://pg-service:3001;
        }

        # Endpointy dotyczące feedu i analityki lecą do mongo-service
        location /api/feed/ {
            proxy_pass http://mongo-service:3002;
        }

        location /api/analytics/ {
            proxy_pass http://mongo-service:3002;
        }
    }
}